a = input('Digite um valor: ')
print(type(a))
print('Alfabetico?', a.isalpha())
print('Alfanumerico?', a.isalnum())
print('Numerico?', a.isnumeric())
print('Decimal?', a.isdecimal())
print('Minusculo?', a.islower())
print('Maiusculo?', a.isupper())
print('Capitalizada?',a.istitle())
